package gr.sr.configsEngine.configs.impl;


import gr.sr.configsEngine.AbstractConfigs;


public class FormulasConfigs extends AbstractConfigs {
    public static boolean ALLOW_HALF_KILL_ON_PLAYERS;
    public static boolean ALLOW_HALF_KILL_ON_MOBS;
    public static boolean ALLOW_HALF_KILL_ON_SUMMONS;
    public static boolean ALLOW_LETHAL_STRIKES_ON_PLAYERS;
    public static boolean ALLOW_LETHAL_STRIKES_ON_MOBS;
    public static boolean ALLOW_LETHAL_STRIKES_ON_SUMMONS;
    public static boolean ALLOW_LETHAL_STRIKES_ON_PLAYERS_CP_ONLY;
    public static int MODIFY_CANCEL_SUCCESS_RATE;
    public static int MAX_RUN_SPEED;
    public static int MAX_PCRIT_RATE;
    public static int MAX_MCRIT_RATE;
    public static int MAX_PATK_SPEED;
    public static int MAX_MATK_SPEED;
    public static int MAX_EVASION;
    public static int MIN_ABNORMAL_STATE_SUCCESS_RATE;
    public static int MAX_ABNORMAL_STATE_SUCCESS_RATE;
    public static float ALT_DAGGER_DMG_VS_HEAVY;
    public static float ALT_DAGGER_DMG_VS_ROBE;
    public static float ALT_DAGGER_DMG_VS_LIGHT;
    public static float ALT_BOW_DMG_VS_HEAVY;
    public static float ALT_BOW_DMG_VS_ROBE;
    public static float ALT_BOW_DMG_VS_LIGHT;
    public static float ALT_CROSSBOW_DMG_VS_HEAVY;
    public static float ALT_CROSSBOW_DMG_VS_ROBE;
    public static float ALT_CROSSBOW_DMG_VS_LIGHT;
    public static float ALT_POLE_DMG_VS_HEAVY;
    public static float ALT_POLE_DMG_VS_ROBE;
    public static float ALT_POLE_DMG_VS_LIGHT;
    public static float ALT_BLUNT_DMG_VS_HEAVY;
    public static float ALT_BLUNT_DMG_VS_ROBE;
    public static float ALT_BLUNT_DMG_VS_LIGHT;
    public static float ALT_SWORD_DMG_VS_HEAVY;
    public static float ALT_SWORD_DMG_VS_ROBE;
    public static float ALT_SWORD_DMG_VS_LIGHT;
    public static float ALT_DUAL_DMG_VS_HEAVY;
    public static float ALT_DUAL_DMG_VS_ROBE;
    public static float ALT_DUAL_DMG_VS_LIGHT;
    public static float ALT_DUAL_FIST_DMG_VS_HEAVY;
    public static float ALT_DUAL_FIST_DMG_VS_ROBE;
    public static float ALT_DUAL_FIST_DMG_VS_LIGHT;
    public static float ALT_ANCIENT_DMG_VS_HEAVY;
    public static float ALT_ANCIENT_DMG_VS_ROBE;
    public static float ALT_ANCIENT_DMG_VS_LIGHT;
    public static float ALT_RAPIER_DMG_VS_HEAVY;
    public static float ALT_RAPIER_DMG_VS_ROBE;
    public static float ALT_RAPIER_DMG_VS_LIGHT;
    public static float ALT_DAGGER_DMG_VS_HEAVY_HIT;
    public static float ALT_DAGGER_DMG_VS_ROBE_HIT;
    public static float ALT_DAGGER_DMG_VS_LIGHT_HIT;
    public static float ALT_BOW_DMG_VS_HEAVY_HIT;
    public static float ALT_BOW_DMG_VS_ROBE_HIT;
    public static float ALT_BOW_DMG_VS_LIGHT_HIT;
    public static float ALT_CROSSBOW_DMG_VS_HEAVY_HIT;
    public static float ALT_CROSSBOW_DMG_VS_ROBE_HIT;
    public static float ALT_CROSSBOW_DMG_VS_LIGHT_HIT;
    public static float ALT_POLE_DMG_VS_HEAVY_HIT;
    public static float ALT_POLE_DMG_VS_ROBE_HIT;
    public static float ALT_POLE_DMG_VS_LIGHT_HIT;
    public static float ALT_BLUNT_DMG_VS_HEAVY_HIT;
    public static float ALT_BLUNT_DMG_VS_ROBE_HIT;
    public static float ALT_BLUNT_DMG_VS_LIGHT_HIT;
    public static float ALT_SWORD_DMG_VS_HEAVY_HIT;
    public static float ALT_SWORD_DMG_VS_ROBE_HIT;
    public static float ALT_SWORD_DMG_VS_LIGHT_HIT;
    public static float ALT_DUAL_DMG_VS_HEAVY_HIT;
    public static float ALT_DUAL_DMG_VS_ROBE_HIT;
    public static float ALT_DUAL_DMG_VS_LIGHT_HIT;
    public static float ALT_DUAL_FIST_DMG_VS_HEAVY_HIT;
    public static float ALT_DUAL_FIST_DMG_VS_ROBE_HIT;
    public static float ALT_DUAL_FIST_DMG_VS_LIGHT_HIT;
    public static float ALT_ANCIENT_DMG_VS_HEAVY_HIT;
    public static float ALT_ANCIENT_DMG_VS_ROBE_HIT;
    public static float ALT_ANCIENT_DMG_VS_LIGHT_HIT;
    public static float ALT_RAPIER_DMG_VS_HEAVY_HIT;
    public static float ALT_RAPIER_DMG_VS_ROBE_HIT;
    public static float ALT_RAPIER_DMG_VS_LIGHT_HIT;
    public static float ALT_MAGIC_DAMAGE_PLAYER_VS_PLAYER;
    public static float ALT_MAGIC_DAMAGE_PLAYER_VS_MOB;
    public static float ALT_MAGIC_DAMAGE_SUMMON_VS_PLAYER;
    public static float ALT_MAGIC_DAMAGE_SUMMON_VS_MOB;
    public static float ALT_MAGIC_DAMAGE_MOB_VS_PLAYER;
    public static float ALT_MAGIC_DAMAGE_MOB_VS_MOB;
    public static float ALT_PHYSICAL_DAMAGE_PLAYER_VS_MOB;
    public static float ALT_PHYSICAL_DAMAGE_SUMMON_VS_PLAYER;
    public static float ALT_PHYSICAL_DAMAGE_SUMMON_VS_MOB;
    public static float ALT_PHYSICAL_DAMAGE_MOB_VS_PLAYER;
    public static float ALT_PHYSICAL_DAMAGE_MOB_VS_MOB;

    public FormulasConfigs() {
    }

    public void loadConfigs() {
        this.loadFile("./config/sunrise/Formulas.ini");
        ALLOW_HALF_KILL_ON_PLAYERS = Boolean.parseBoolean(this.getString(this._settings, this._override, "AllowHalfKillsOnPlayers", "True"));
        ALLOW_HALF_KILL_ON_MOBS = Boolean.parseBoolean(this.getString(this._settings, this._override, "AllowHalfKillsOnMobs", "True"));
        ALLOW_HALF_KILL_ON_SUMMONS = Boolean.parseBoolean(this.getString(this._settings, this._override, "AllowHalfKillsOnSummons", "True"));
        ALLOW_LETHAL_STRIKES_ON_PLAYERS = Boolean.parseBoolean(this.getString(this._settings, this._override, "AllowLethalStrikesOnPlayers", "True"));
        ALLOW_LETHAL_STRIKES_ON_MOBS = Boolean.parseBoolean(this.getString(this._settings, this._override, "AllowLethalStrikesOnMobs", "True"));
        ALLOW_LETHAL_STRIKES_ON_SUMMONS = Boolean.parseBoolean(this.getString(this._settings, this._override, "AllowLethalStrikesOnSummons", "True"));
        ALLOW_LETHAL_STRIKES_ON_PLAYERS_CP_ONLY = Boolean.parseBoolean(this.getString(this._settings, this._override, "AllowLethalStrikesOnPlayersCpOnly", "False"));
        MODIFY_CANCEL_SUCCESS_RATE = Integer.parseInt(this.getString(this._settings, this._override, "ModifyCancelSuccessRate", "0"));
        MAX_RUN_SPEED = Integer.parseInt(this.getString(this._settings, this._override, "MaxRunSpeed", "250"));
        MAX_PCRIT_RATE = Integer.parseInt(this.getString(this._settings, this._override, "MaxPCritRate", "500"));
        MAX_MCRIT_RATE = Integer.parseInt(this.getString(this._settings, this._override, "MaxMCritRate", "200"));
        MAX_PATK_SPEED = Integer.parseInt(this.getString(this._settings, this._override, "MaxPAtkSpeed", "1500"));
        MAX_MATK_SPEED = Integer.parseInt(this.getString(this._settings, this._override, "MaxMAtkSpeed", "1999"));
        MAX_EVASION = Integer.parseInt(this.getString(this._settings, this._override, "MaxEvasion", "250"));
        MIN_ABNORMAL_STATE_SUCCESS_RATE = Integer.parseInt(this.getString(this._settings, this._override, "MinAbnormalStateSuccessRate", "10"));
        MAX_ABNORMAL_STATE_SUCCESS_RATE = Integer.parseInt(this.getString(this._settings, this._override, "MaxAbnormalStateSuccessRate", "90"));
        ALT_DAGGER_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "DaggerVSHeavy", "2.50"));
        ALT_DAGGER_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "DaggerVSRobe", "1.80"));
        ALT_DAGGER_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "DaggerVSLight", "2.00"));
        ALT_BOW_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "ArcherVSHeavy", "1.00"));
        ALT_BOW_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "ArcherVSRobe", "1.00"));
        ALT_BOW_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "ArcherVSLight", "1.00"));
        ALT_CROSSBOW_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "TricksterVSHeavy", "1.00"));
        ALT_CROSSBOW_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "TricksterVSRobe", "1.00"));
        ALT_CROSSBOW_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "TricksterVSLight", "1.00"));
        ALT_POLE_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "PoleVSHeavy", "1.00"));
        ALT_POLE_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "PoleVSRobe", "1.00"));
        ALT_POLE_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "PoleVSLight", "1.00"));
        ALT_BLUNT_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "BluntVSHeavy", "1.00"));
        ALT_BLUNT_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "BluntVSRobe", "1.00"));
        ALT_BLUNT_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "BluntVSLight", "1.00"));
        ALT_SWORD_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "SwordVSHeavy", "1.00"));
        ALT_SWORD_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "SwordVSRobe", "1.00"));
        ALT_SWORD_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "SwordVSLight", "1.00"));
        ALT_DUAL_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "DualVSHeavy", "1.00"));
        ALT_DUAL_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "DualVSRobe", "1.00"));
        ALT_DUAL_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "DualVSLight", "1.00"));
        ALT_DUAL_FIST_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "DualFistVSHeavy", "1.00"));
        ALT_DUAL_FIST_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "DualFistVSRobe", "1.00"));
        ALT_DUAL_FIST_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "DualFistVSLight", "1.00"));
        ALT_ANCIENT_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "AncientVSHeavy", "1.00"));
        ALT_ANCIENT_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "AncientVSRobe", "1.00"));
        ALT_ANCIENT_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "AncientVSLight", "1.00"));
        ALT_RAPIER_DMG_VS_HEAVY = Float.parseFloat(this.getString(this._settings, this._override, "RapierVSHeavy", "1.00"));
        ALT_RAPIER_DMG_VS_ROBE = Float.parseFloat(this.getString(this._settings, this._override, "RapierVSRobe", "1.00"));
        ALT_RAPIER_DMG_VS_LIGHT = Float.parseFloat(this.getString(this._settings, this._override, "RapierVSLight", "1.00"));
        ALT_DAGGER_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "DaggerVSHeavyHit", "2.50"));
        ALT_DAGGER_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "DaggerVSRobeHit", "1.80"));
        ALT_DAGGER_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "DaggerVSLightHit", "2.00"));
        ALT_BOW_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "ArcherVSHeavyHit", "1.00"));
        ALT_BOW_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "ArcherVSRobeHit", "1.00"));
        ALT_BOW_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "ArcherVSLightHit", "1.00"));
        ALT_CROSSBOW_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "TricksterVSHeavyHit", "1.00"));
        ALT_CROSSBOW_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "TricksterVSRobeHit", "1.00"));
        ALT_CROSSBOW_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "TricksterVSLightHit", "1.00"));
        ALT_POLE_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "PoleVSHeavyHit", "1.00"));
        ALT_POLE_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "PoleVSRobeHit", "1.00"));
        ALT_POLE_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "PoleVSLightHit", "1.00"));
        ALT_BLUNT_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "BluntVSHeavyHit", "1.00"));
        ALT_BLUNT_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "BluntVSRobeHit", "1.00"));
        ALT_BLUNT_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "BluntVSLightHit", "1.00"));
        ALT_SWORD_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "SwordVSHeavyHit", "1.00"));
        ALT_SWORD_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "SwordVSRobeHit", "1.00"));
        ALT_SWORD_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "SwordVSLightHit", "1.00"));
        ALT_DUAL_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "DualVSHeavyHit", "1.00"));
        ALT_DUAL_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "DualVSRobeHit", "1.00"));
        ALT_DUAL_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "DualVSLightHit", "1.00"));
        ALT_DUAL_FIST_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "DualFistVSHeavyHit", "1.00"));
        ALT_DUAL_FIST_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "DualFistVSRobeHit", "1.00"));
        ALT_DUAL_FIST_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "DualFistVSLightHit", "1.00"));
        ALT_ANCIENT_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "AncientVSHeavyHit", "1.00"));
        ALT_ANCIENT_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "AncientVSRobeHit", "1.00"));
        ALT_ANCIENT_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "AncientVSLightHit", "1.00"));
        ALT_RAPIER_DMG_VS_HEAVY_HIT = Float.parseFloat(this.getString(this._settings, this._override, "RapierVSHeavyHit", "1.00"));
        ALT_RAPIER_DMG_VS_ROBE_HIT = Float.parseFloat(this.getString(this._settings, this._override, "RapierVSRobeHit", "1.00"));
        ALT_RAPIER_DMG_VS_LIGHT_HIT = Float.parseFloat(this.getString(this._settings, this._override, "RapierVSLightHit", "1.00"));
        ALT_MAGIC_DAMAGE_PLAYER_VS_PLAYER = Float.parseFloat(this.getString(this._settings, this._override, "AltMagicDamagePlayerVSPlayer", "1.00"));
        ALT_MAGIC_DAMAGE_PLAYER_VS_MOB = Float.parseFloat(this.getString(this._settings, this._override, "AltMagicDamagePlayerVSMob", "1.00"));
        ALT_MAGIC_DAMAGE_SUMMON_VS_PLAYER = Float.parseFloat(this.getString(this._settings, this._override, "AltMagicDamageSummonVSPlayer", "1.00"));
        ALT_MAGIC_DAMAGE_SUMMON_VS_MOB = Float.parseFloat(this.getString(this._settings, this._override, "AltMagicDamageSummonVSMob", "1.00"));
        ALT_MAGIC_DAMAGE_MOB_VS_PLAYER = Float.parseFloat(this.getString(this._settings, this._override, "AltMagicDamageMobVSPlayer", "1.00"));
        ALT_MAGIC_DAMAGE_MOB_VS_MOB = Float.parseFloat(this.getString(this._settings, this._override, "AltMagicDamageMobVSMob", "1.00"));
        ALT_PHYSICAL_DAMAGE_PLAYER_VS_MOB = Float.parseFloat(this.getString(this._settings, this._override, "AltPhysicalDamagePlayerVSMob", "1.00"));
        ALT_PHYSICAL_DAMAGE_SUMMON_VS_PLAYER = Float.parseFloat(this.getString(this._settings, this._override, "AltPhysicalDamageSummonVSPlayer", "1.00"));
        ALT_PHYSICAL_DAMAGE_SUMMON_VS_MOB = Float.parseFloat(this.getString(this._settings, this._override, "AltPhysicalDamageSummonVSMob", "1.00"));
        ALT_PHYSICAL_DAMAGE_MOB_VS_PLAYER = Float.parseFloat(this.getString(this._settings, this._override, "AltPhysicalDamageMobVSPlayer", "1.00"));
        ALT_PHYSICAL_DAMAGE_MOB_VS_MOB = Float.parseFloat(this.getString(this._settings, this._override, "AltPhysicalDamageMobVSMob", "1.00"));
    }

    protected static FormulasConfigs instance;

    public static FormulasConfigs getInstance() {
        if (instance == null)
            instance = new FormulasConfigs();
        return instance;
    }
}
